In [1]:
import numpy as np

In [2]:
c = range(10000)

In [3]:
%timeit [i**3 for i in c]

9.39 ms ± 927 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
c_numpy = np.arange(10000)

In [5]:
%timeit c_numpy**3

50.2 µs ± 2.85 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
l1 = range(10000)
l2 = [i**2 for i in range (10000)]

In [7]:
%timeit list(map(lambda x, y: x*y, l1, l2))

3.75 ms ± 436 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
a = np.array(l1)
b = np.array(l2)

In [10]:
%timeit a*b

19.8 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Creating Numpy Array

In [11]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [20]:
np.full((4,4),75.2, dtype = int)

array([[75, 75, 75, 75],
       [75, 75, 75, 75],
       [75, 75, 75, 75],
       [75, 75, 75, 75]])

In [21]:
np.diag([75, 77, 81])

array([[75,  0,  0],
       [ 0, 77,  0],
       [ 0,  0, 81]])

In [22]:
v = np.array([1,2,3])

In [23]:
v

array([1, 2, 3])

In [25]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [26]:
np.random.random()

0.43196428069296333

In [29]:
50*np.random.random()

19.241681064487477

In [30]:
np.random.random([4,4])

array([[0.69526914, 0.78991834, 0.53562627, 0.83508819],
       [0.96010328, 0.95543396, 0.89314145, 0.26064415],
       [0.88661201, 0.51189694, 0.15613423, 0.25273584],
       [0.07976156, 0.66716113, 0.20032334, 0.70998927]])

In [ ]:
a = np.linspace(1,50,100)

In [33]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [34]:
a.itemsize

8

In [35]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
np.arange(18).reshape(2,3,-1)